### ISSUE TITLE
Add `testRenderer` lint rule

### ISSUE THREAD

**Issue by craigbilner** [newsuk/times-components#1058]
**Do you want to request a _feature_ or report a _bug_?**

feature

**What is the current behaviour?**

It's possible to use different naming conventions within tests

**What is the expected behaviour?**

Fails linting if the variable used for `TestRenderer.create` is not `testRenderer`

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

To make test code style consistent

**Comment by nathggns** [comment]
Could you please explain to me why enforcing variable names in tests is helpful? I agree conventions can be helpful but only when they bring value, and I'm not sure what the value is here? Just seems like bike shedding.

The variable names here are inconsequential. Any name is arbitrary. They don't tell you anything. Inconsistency isn't bad in and of itself, its a sign that you're doing something wrong. But in this case its just arbitrary, so why enforce it?

Consistency is valuable when it brings value, but I'm wary of extra lint steps that don't seem to bring any value.

**Comment by colincclark** [comment]
Computers don't read our pre-compiled code, developers do. Although choosing variable names is an arbitrary process, it is important that we make them readable and meaningful. The consistency and meaning in these variable names help reduce mental effort for the developers that will come after us, who read the code. The variable name referred to in this issue was lifted from the documentation in `react-test-renderer` (see https://reactjs.org/docs/test-renderer.html). This issue should actually be extended to help differentiate between objects:

```
const testRenderer = TestRenderer.create(<MyComponent />);
const testInstance = testRenderer.root;
```

Variable names do matter. They should be clear, concise, and consistent. That is what the eslint rule would allow us to have, and the lint overhead would be neglible. It would be ideal if we implemented a `--fix` option that would change these var names so there was no extra effort in ensuring the consistency manually when developing.
