### ISSUE TITLE
Provide a more useful mock result when requiring an image in React Native

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#1102]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behaviour?**

We need to mock image assets to get meaningful `source` attributes on RN Image components. This is not ideal

**What is the expected behaviour?**

we should provide a better mapping feature that surfaces something meaningful in the snapshot without having to mock each image. See https://github.com/facebook/jest/issues/2838 for inspiration

**If this is a feature request, what is the motivation or use case for changing
the behaviour?**

Removes the need to mock each asset, and should also affect snapshots when asset paths change

**Comment by nathggns** [comment]
Investigating this now… seems React Native does support this https://github.com/facebook/react-native/pull/13319 – not sure why it isn't working.

**Comment by nathggns** [comment]
Okay, so it wasn't working because `jest-configurator` was providing its own `moduleNameMapper` for `png`s (`RelativeImageStub`). I did try removing this but didn't realise I needed to manually re-transpile `jest-configurator`. **This is probably something worth adding to the docs**

The good news is that `react-native`'s preset should work for what we need here if we remove our own `moduleNameMapper` for `png`s on native. 

The bad news is that in the version of `react-native` we use, the `react-native` preset isn't setup to transform scoped packages – https://github.com/facebook/react-native/issues/17879

This was fixed in https://github.com/facebook/react-native/commit/216bce31632480ce70cc03b1b2a57ec12440afd7 which landed in `v0.56.0`.

So, either we need to update `react-native`, or just update the config so it uses the correct regex for the transform.

**Comment by nathggns** [comment]
Potential issue if we tried to update react-native – Expo doesn't seem to support React Native 56 yet. 

https://docs.expo.io/versions/latest/sdk/index.html

![image](https://user-images.githubusercontent.com/719814/47148006-66cf8100-d2c7-11e8-9e51-503917e4186a.png)
