### ISSUE TITLE
Remove flow

### ISSUE THREAD

**Issue by colincclark** [newsuk/times-components#1421]
**Do you want to request a _feature_ or report a _bug_?**

Refactor

**What is the current behaviour?**

Flow is in the tracking, jest-configurator and jest-serialiser packages and the business has decided to move to typescript at some point in the future so flow should be removed ASAP. This is to ensure it is not confusing to new starters that flow is the way to go so to speak.

**Comment by jimhunty** [comment]
I agree that Flow needs to go. I think if our direction is TypeScript, it would be easier at this point to move the current implementations of these packages to TypeScript rather than remove.

If this was the case then we should also take the initiative to update the component cli to create ts packages and start adopting it properly. Otherwise we should remove and tackle this question further down the line.

**Comment by nathggns** [comment]
Moving to TypeScript takes a not insignificant amount of work. Removing flow does not, and the current state is not really desirable. Therefore, I'm of the view that it'd be better to remove flow first, and then look at gradually adding TypeScript as contributors desire to, than to keep the flow until someone has the time to convert it. 

After all, the flow code doesn't disappear. We use version control for a reason.

**Comment by colincclark** [comment]
Done in https://github.com/newsuk/times-components/pull/1467
